# Generated by Django 4.2.11 on 2024-04-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_uploadedfile_delete_uploadfileform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
