# Generated by Django 4.2.11 on 2024-04-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0007_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
    ]
