# Generated by Django 4.2.11 on 2024-04-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0009_myconnector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyConnector',
        ),
    ]
