# Generated by Django 4.2.11 on 2024-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0010_delete_myconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgresconnector',
            name='database_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
