# Generated by Django 4.2.11 on 2024-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0012_alter_my_connector_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_connector',
            name='service_name',
            field=models.CharField(default='mysql'),
        ),
    ]
