# Generated by Django 4.2.11 on 2024-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0013_alter_my_connector_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_connector',
            name='service_name',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], max_length=10),
        ),
    ]
